#!/usr/bin/env bash
# This script prints a str 110 time with exception"

count=0
while [ $count -lt 10 ]; do
    if [ $count -eq 8 ]
    then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi
    (( count=count+1))
done
